version: '2'
services:
  mysql:
    image: lbanchio/mysql
    hostname: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: parcial2
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000

  adminer:
    image: adminer
    ports:
      - 8080:8080
